// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DocumentResponse {
    /**
     * Creates a new DocumentResponse instance.
     * @param {Partial<DocumentResponse>} [$$source = {}] - The source object to create the DocumentResponse.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("documentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["documentType"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mimeType"] = undefined;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["html"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["contentBase64"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocumentResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocumentResponse(/** @type {Partial<DocumentResponse>} */($$parsedSource));
    }
}

export class TreeNode {
    /**
     * Creates a new TreeNode instance.
     * @param {Partial<TreeNode>} [$$source = {}] - The source object to create the TreeNode.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["documentType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mimeType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["size"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TreeNode[] | undefined}
             */
            this["children"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TreeNode}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField7_0($$parsedSource["children"]);
        }
        return new TreeNode(/** @type {Partial<TreeNode>} */($$parsedSource));
    }
}

export class UnlockResponse {
    /**
     * Creates a new UnlockResponse instance.
     * @param {Partial<UnlockResponse>} [$$source = {}] - The source object to create the UnlockResponse.
     */
    constructor($$source = {}) {
        if (!("tree" in $$source)) {
            /**
             * @member
             * @type {TreeNode[]}
             */
            this["tree"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnlockResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UnlockResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tree" in $$parsedSource) {
            $$parsedSource["tree"] = $$createField0_0($$parsedSource["tree"]);
        }
        return new UnlockResponse(/** @type {Partial<UnlockResponse>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = TreeNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
