// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DocumentResponse {
    "id": string;
    "title": string;
    "documentType": string;
    "mimeType"?: string;
    "size": number;
    "html"?: string;
    "contentBase64"?: string;
    "chunked"?: boolean;
    "chunkSize"?: number;
    "chunkCount"?: number;

    /** Creates a new DocumentResponse instance. */
    constructor($$source: Partial<DocumentResponse> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("documentType" in $$source)) {
            this["documentType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocumentResponse($$parsedSource as Partial<DocumentResponse>);
    }
}

export class PDFChunkResponse {
    "id": string;
    "index": number;
    "offset": number;
    "size": number;
    "chunkCount": number;
    "contentBase64": string;

    /** Creates a new PDFChunkResponse instance. */
    constructor($$source: Partial<PDFChunkResponse> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("chunkCount" in $$source)) {
            this["chunkCount"] = 0;
        }
        if (!("contentBase64" in $$source)) {
            this["contentBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PDFChunkResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): PDFChunkResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PDFChunkResponse($$parsedSource as Partial<PDFChunkResponse>);
    }
}

export class TreeNode {
    "id"?: string;
    "title": string;
    "path": string;
    "kind": string;
    "documentType"?: string;
    "mimeType"?: string;
    "size"?: number;
    "children"?: TreeNode[];

    /** Creates a new TreeNode instance. */
    constructor($$source: Partial<TreeNode> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): TreeNode {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField7_0($$parsedSource["children"]);
        }
        return new TreeNode($$parsedSource as Partial<TreeNode>);
    }
}

export class UnlockResponse {
    "tree": TreeNode[];

    /** Creates a new UnlockResponse instance. */
    constructor($$source: Partial<UnlockResponse> = {}) {
        if (!("tree" in $$source)) {
            this["tree"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnlockResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): UnlockResponse {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tree" in $$parsedSource) {
            $$parsedSource["tree"] = $$createField0_0($$parsedSource["tree"]);
        }
        return new UnlockResponse($$parsedSource as Partial<UnlockResponse>);
    }
}

// Private type creation functions
const $$createType0 = TreeNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
