// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AIChatRequest 由前端发起的划词 AI 解读请求。
 */
export class AIChatRequest {
    "requestId": number;
    "documentId": string;
    "selectedText": string;
    "question": string;
    "history": AIMessage[];

    /**
     * Model 为前端选中的模型名；为空时后端使用配置列表首个。
     */
    "model"?: string;

    /** Creates a new AIChatRequest instance. */
    constructor($$source: Partial<AIChatRequest> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = 0;
        }
        if (!("documentId" in $$source)) {
            this["documentId"] = "";
        }
        if (!("selectedText" in $$source)) {
            this["selectedText"] = "";
        }
        if (!("question" in $$source)) {
            this["question"] = "";
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIChatRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AIChatRequest {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField4_0($$parsedSource["history"]);
        }
        return new AIChatRequest($$parsedSource as Partial<AIChatRequest>);
    }
}

/**
 * AIInfo 返回当前可用的 AI 配置信息（不含 apiKey），供前端展示与可用性判断。
 * Models 为全部可选模型（access.yaml 的 ai.models，旧单值 ai.model 时仅含一个）。
 */
export class AIInfo {
    "available": boolean;
    "model"?: string;
    "models"?: string[];
    "endpoint"?: string;

    /** Creates a new AIInfo instance. */
    constructor($$source: Partial<AIInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AIInfo {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField2_0($$parsedSource["models"]);
        }
        return new AIInfo($$parsedSource as Partial<AIInfo>);
    }
}

/**
 * AIMessage 是一条对话消息，role 为 user 或 assistant。
 */
export class AIMessage {
    "role": string;
    "content": string;

    /** Creates a new AIMessage instance. */
    constructor($$source: Partial<AIMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): AIMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIMessage($$parsedSource as Partial<AIMessage>);
    }
}

export class DocumentResponse {
    "id": string;
    "title": string;
    "documentType": string;
    "mimeType"?: string;
    "size": number;
    "html"?: string;
    "contentBase64"?: string;
    "chunked"?: boolean;
    "chunkSize"?: number;
    "chunkCount"?: number;

    /** Creates a new DocumentResponse instance. */
    constructor($$source: Partial<DocumentResponse> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("documentType" in $$source)) {
            this["documentType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocumentResponse($$parsedSource as Partial<DocumentResponse>);
    }
}

export class PDFChunkResponse {
    "id": string;
    "index": number;
    "offset": number;
    "size": number;
    "chunkCount": number;
    "contentBase64": string;

    /** Creates a new PDFChunkResponse instance. */
    constructor($$source: Partial<PDFChunkResponse> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("chunkCount" in $$source)) {
            this["chunkCount"] = 0;
        }
        if (!("contentBase64" in $$source)) {
            this["contentBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PDFChunkResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): PDFChunkResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PDFChunkResponse($$parsedSource as Partial<PDFChunkResponse>);
    }
}

/**
 * SecurityPolicy 返回运行时安全策略信息，供宿主（main.go）注入 CSP 使用。
 * 不含任何密钥或文档内容。
 */
export class SecurityPolicy {
    "allowRemoteImages": boolean;

    /** Creates a new SecurityPolicy instance. */
    constructor($$source: Partial<SecurityPolicy> = {}) {
        if (!("allowRemoteImages" in $$source)) {
            this["allowRemoteImages"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecurityPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): SecurityPolicy {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecurityPolicy($$parsedSource as Partial<SecurityPolicy>);
    }
}

export class TreeNode {
    "id"?: string;
    "title": string;
    "path": string;
    "kind": string;
    "documentType"?: string;
    "mimeType"?: string;
    "size"?: number;
    "children"?: TreeNode[];

    /** Creates a new TreeNode instance. */
    constructor($$source: Partial<TreeNode> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): TreeNode {
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField7_0($$parsedSource["children"]);
        }
        return new TreeNode($$parsedSource as Partial<TreeNode>);
    }
}

export class UnlockResponse {
    "tree": TreeNode[];

    /** Creates a new UnlockResponse instance. */
    constructor($$source: Partial<UnlockResponse> = {}) {
        if (!("tree" in $$source)) {
            this["tree"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnlockResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): UnlockResponse {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tree" in $$parsedSource) {
            $$parsedSource["tree"] = $$createField0_0($$parsedSource["tree"]);
        }
        return new UnlockResponse($$parsedSource as Partial<UnlockResponse>);
    }
}

// Private type creation functions
const $$createType0 = AIMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = TreeNode.createFrom;
const $$createType4 = $Create.Array($$createType3);
