// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetDocument(id: string): $CancellablePromise<$models.DocumentResponse> {
    return $Call.ByID(1841490028, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetTree(): $CancellablePromise<$models.TreeNode[]> {
    return $Call.ByID(2630704765).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(2281858988);
}

export function Unlock(password: string): $CancellablePromise<$models.UnlockResponse> {
    return $Call.ByID(2110480459, password).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DocumentResponse.createFrom;
const $$createType1 = $models.TreeNode.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.UnlockResponse.createFrom;
