// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.DocumentResponse>}
 */
export function GetDocument(id) {
    return $Call.ByID(1841490028, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.TreeNode[]>}
 */
export function GetTree() {
    return $Call.ByID(2630704765).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Lock() {
    return $Call.ByID(2281858988);
}

/**
 * @param {string} password
 * @returns {$CancellablePromise<$models.UnlockResponse>}
 */
export function Unlock(password) {
    return $Call.ByID(2110480459, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DocumentResponse.createFrom;
const $$createType1 = $models.TreeNode.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.UnlockResponse.createFrom;
