package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"cryptowitch/internal/vault"
	"gopkg.in/yaml.v3"
)

type appConfig struct {
	App struct {
		Title string `yaml:"title"`
	} `yaml:"app"`
	Vault struct {
		Password string `yaml:"password"`
		KDF      struct {
			Time    uint32 `yaml:"time"`
			Memory  uint32 `yaml:"memory"`
			Threads uint8  `yaml:"threads"`
			KeyLen  uint32 `yaml:"keyLen"`
		} `yaml:"kdf"`
	} `yaml:"vault"`
}

func main() {
	configPath := flag.String("config", "config.yaml", "build-time app config")
	contentDir := flag.String("content", "content/plain", "plain markdown content directory")
	outputPath := flag.String("out", "internal/vault/generated.go", "generated Go vault output")
	flag.Parse()

	if err := run(*configPath, *contentDir, *outputPath); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(configPath, contentDir, outputPath string) error {
	config, err := readConfig(configPath)
	if err != nil {
		return err
	}
	documents, err := readDocuments(contentDir)
	if err != nil {
		return err
	}
	if len(documents) == 0 {
		return errors.New("no markdown documents found")
	}

	encrypted, err := vault.EncryptVault(vault.PlainVault{Documents: documents}, config.Vault.Password, vault.KDFParams{
		Time:    config.Vault.KDF.Time,
		Memory:  config.Vault.KDF.Memory,
		Threads: config.Vault.KDF.Threads,
		KeyLen:  config.Vault.KDF.KeyLen,
	})
	if err != nil {
		return err
	}

	generated, err := renderGeneratedVault(encrypted)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := os.WriteFile(outputPath, generated, 0o644); err != nil {
		return fmt.Errorf("write generated vault: %w", err)
	}
	return nil
}

func readConfig(path string) (appConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return appConfig{}, fmt.Errorf("read config: %w", err)
	}
	var config appConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return appConfig{}, fmt.Errorf("parse config: %w", err)
	}
	if config.Vault.Password == "" {
		return appConfig{}, errors.New("vault.password is required")
	}
	return config, nil
}

func readDocuments(root string) ([]vault.PlainDocument, error) {
	var documents []vault.PlainDocument
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || strings.ToLower(filepath.Ext(entry.Name())) != ".md" {
			return nil
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read document %s: %w", path, err)
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return fmt.Errorf("resolve document path %s: %w", path, err)
		}
		normalizedPath := filepath.ToSlash(relative)
		documents = append(documents, vault.PlainDocument{
			ID:      documentID(normalizedPath),
			Title:   documentTitle(entry.Name(), string(data)),
			Path:    normalizedPath,
			Content: string(data),
		})
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("scan content: %w", err)
	}
	sort.Slice(documents, func(i, j int) bool {
		return documents[i].Path < documents[j].Path
	})
	return documents, nil
}

func documentID(path string) string {
	sum := sha256.Sum256([]byte(path))
	return base64.RawURLEncoding.EncodeToString(sum[:12])
}

func documentTitle(filename string, content string) string {
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "# ") {
			return strings.TrimSpace(strings.TrimPrefix(trimmed, "# "))
		}
	}
	return strings.TrimSuffix(filename, filepath.Ext(filename))
}

func renderGeneratedVault(encrypted vault.EncryptedVault) ([]byte, error) {
	var buffer bytes.Buffer
	buffer.WriteString("package vault\n\n")
	buffer.WriteString("// Code generated by `go run ./cmd/packdocs`; DO NOT EDIT.\n")
	buffer.WriteString("var EmbeddedVault = EncryptedVault{\n")
	buffer.WriteString(fmt.Sprintf("\tVersion: %d,\n", encrypted.Version))
	buffer.WriteString("\tKDF: KDFParams{\n")
	buffer.WriteString(fmt.Sprintf("\t\tTime: %d,\n", encrypted.KDF.Time))
	buffer.WriteString(fmt.Sprintf("\t\tMemory: %d,\n", encrypted.KDF.Memory))
	buffer.WriteString(fmt.Sprintf("\t\tThreads: %d,\n", encrypted.KDF.Threads))
	buffer.WriteString(fmt.Sprintf("\t\tKeyLen: %d,\n", encrypted.KDF.KeyLen))
	buffer.WriteString("\t},\n")
	buffer.WriteString(fmt.Sprintf("\tSalt:       %s,\n", byteSliceLiteral(encrypted.Salt)))
	buffer.WriteString(fmt.Sprintf("\tNonce:      %s,\n", byteSliceLiteral(encrypted.Nonce)))
	buffer.WriteString(fmt.Sprintf("\tCiphertext: %s,\n", byteSliceLiteral(encrypted.Ciphertext)))
	buffer.WriteString("}\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated vault: %w", err)
	}
	return formatted, nil
}

func byteSliceLiteral(data []byte) string {
	var buffer bytes.Buffer
	buffer.WriteString("[]byte{")
	for i, value := range data {
		if i > 0 {
			buffer.WriteString(", ")
		}
		buffer.WriteString(fmt.Sprintf("0x%02x", value))
	}
	buffer.WriteString("}")
	return buffer.String()
}
